server:
  http:
    addr: 0.0.0.0:10300
    timeout: 1s
  grpc:
    addr: 0.0.0.0:10301
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:10020)/user_center?parseTime=true
  redis:
    addr: 127.0.0.1:10030
    read_timeout: 0.2s
    write_timeout: 0.2s